version: 2.1

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          context: cypress-circleci-env

jobs:
  build-and-test:
    docker:
      - image: circleci/buildpack-deps:stable
    working_directory: ~/mattermost-e2e
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker-compose -f docker-compose.server.yml up -d
      - run:
          name: Wait for Inbucket
          command: |
            until curl --max-time 5 --output - localhost:10080; do echo waiting for Inbucket; sleep 5; done;
      - run:
          name: Wait for Elasticsearch
          command: |
            until curl --max-time 5 --output - localhost:9000; do echo waiting for Elasticsearch; sleep 5; done;