version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: cypress/browsers:node10.16.3-chrome80-ff73
      - image: mattermost/mattermost-prod-db:latest
        environment:
          POSTGRES_USER: mmuser
          POSTGRES_PASSWORD: mostest
          POSTGRES_DB: mattermost_test
      - image: jhillyerd/inbucket:release-1.2.0
      - image: osixia/openldap:1.2.2
        environment:
          LDAP_TLS_VERIFY_CLIENT: "never"
          LDAP_ORGANISATION: "Mattermost Test"
          LDAP_DOMAIN: "mm.test.com"
          LDAP_ADMIN_PASSWORD: "mostest"
      - image: minio/minio:RELEASE.2019-10-11T00-38-09Z
        environment:
          MINIO_ACCESS_KEY: minioaccesskey
          MINIO_SECRET_KEY: miniosecretkey
          MINIO_SSE_MASTER_KEY: "my-minio-key:6368616e676520746869732070617373776f726420746f206120736563726574"
      - image: mattermost/mattermost-elasticsearch-docker:6.5.1
        environment:
          http.host: "0.0.0.0"
          http.port: 9200
          http.cors.enabled: "true"
          http.cors.allow-origin: "http://localhost:1358,http://127.0.0.1:1358"
          http.cors.allow-headers: "X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
          http.cors.allow-credentials: "true"
          transport.host: "127.0.0.1"
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      - image: mattermost/mattermost-enterprise-edition:master
          environment:
            DB_HOST: loclhost
            DB_PORT_NUMBER: 5432
            MM_DBNAME: mattermost_test
            MM_USERNAME: mmuser
            MM_PASSWORD: mostest
    working_directory: ~/mattermost-cypress-docker
    environment:
      COMPOSE_PROJECT_NAME: "circleci"
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: ~/mattermost-cypress-docker
      - run:
          name: Checks
          command: |
            pwd
            ls -rtl
      # - run:
      #     name: Install Docker client
      #     command: apk add docker-cli
      # - run:
      #     name: Install Docker Compose
      #     command: |
      #       set -x
      #       curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
      #       chmod +x /usr/local/bin/docker-compose
      - run:
          name: install-npm
          command: cd e2e && npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./e2e/node_modules
      - run: # run tests
          name: test
          command: cd e2e && npm run test:ci
workflows:
    build-and-test:
      jobs:
        - build-and-test
