version: '2.4'
services:
  postgres:
    extends:
        file: docker-compose.common.yml
        service: postgres
    tmpfs: /var/lib/postgresql/data
  minio:
    extends:
        file: docker-compose.common.yml
        service: minio
  inbucket:
    extends:
        file: docker-compose.common.yml
        service: inbucket
  openldap:
    extends:
        file: docker-compose.common.yml
        service: openldap
  elasticsearch:
    extends:
        file: docker-compose.common.yml
        service: elasticsearch

  start_dependencies:
    image: mattermost/mattermost-wait-for-dep:latest
    networks:
      - mm-test
    depends_on:
      - postgres
      - minio
      - inbucket
      - openldap
      - elasticsearch
    command: postgres:5432 minio:9000 inbucket:10080 openldap:389 elasticsearch:9200

  app:
    build: app
    networks:
      - mm-test
    depends_on: 
      - start_dependencies
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment: 
      MM_USERNAME: mmuser
      MM_PASSWORD: mmuser_password
      MM_DBNAME: mattermost
      MM_EMAILSETTINGS_SMTPSERVER: inbucket
      MM_EMAILSETTINGS_SMTPPORT: 10025
      MM_ELASTICSEARCHSETTINGS_CONNECTIONURL: http://elasticsearch:9200
      MM_SQLSETTINGS_DATASOURCE: "postgres://mmuser:mostest@postgres:5432/migrated?sslmode=disable&connect_timeout=10"
      MM_SQLSETTINGS_DRIVERNAME: postgres
    ports:
      - "8000:8000"

  # webhook:
  #   build: webhook
  #   networks:
  #     - mm-test
  #   depends_on: 
  #     - start_dependencies
  #   environment:
  #     CYPRESS_baseUrl: http://app:8000

networks:
  mm-test:
    driver: bridge
